"""Reviewed lesson vocabulary and prerequisite links, keyed by stable class names."""
from dataclasses import dataclass


@dataclass(frozen=True)
class Connection:
    text: str
    previous: tuple[str, ...]


# Original lesson IDs stay fixed when section summaries are inserted.
# These IDs are resolved to classes once the original registry has been built.
REVIEW = {
1: ((), 'Separate update rate, signal frequency and response bandwidth. A 1 kHz controller updates every 1 ms; that does not make its mechanical response a 1 kHz response.'),
2: ((1,), 'Name the input, output and operating point before naming model order. The same motor can have a first-order torque-to-speed model and a second-order torque-to-position model.'),
3: ((2,), 'J is rotational inertia, b is viscous damping and k is stiffness. These measured parameters belong to a stated model and configuration; they are not controller gains.'),
4: ((3,1), 'Physical J, b and k stay in the plant. Substituting feedback changes the closed-loop equation; virtual stiffness or damping is achieved only within actuator and timing limits.'),
5: ((3,4), 'For Jω̇ + bω = τ_motor, more J at fixed b means a larger time constant J/b. At the same torque step, acceleration is initially smaller but final speed τ_motor/b is unchanged.'),
6: ((5,), 'τ_c is a duration, p = −1/τ_c is a pole, and f_bw = 1/(2πτ_c) is a bandwidth in Hz. Doubling J at fixed b doubles rise and settling times in this first-order speed model.'),
7: ((5,6), 'With no drain, Jω̇ = τ_motor has no finite J/b time constant. Constant torque ramps speed; integrating speed adds a position state. A double integrator is not marginally stable.'),
8: ((6,1), 'For this first-order low-pass, angular bandwidth is 1/τ_c in rad/s; bandwidth in Hz is 1/(2πτ_c). Neither is the sample rate. The input/output pair stays the same as in the step response.'),
9: ((6,7), 'A pole’s real part sets growth or decay. Its imaginary part sets oscillation. A bounded zero-input response on the imaginary axis need not stay bounded under a continuing input.'),
10: ((9,4), 'Free vibration means no continuing input. Initial position and velocity set amplitude and phase; damping determines decay. This becomes the transient part of later forced responses.'),
11: ((10,6), 'For Jθ̈ + B_total θ̇ + K_total θ = input, ω_n = √(K_total/J) and ζ = B_total/(2√(JK_total)). More inertia at fixed gains changes both; the first-order J/b settling rule does not transfer unchanged.'),
12: ((9,7), 'Asymptotic stability, marginal zero-input stability and bounded-input bounded-output stability are different claims. Specify which response and which poles you are discussing.'),
13: ((8,11,12), 'Read gain crossover and margins from loop gain L. Read tracking bandwidth from closed-loop response T. A mapping from phase margin to damping ratio needs a specified loop model.'),
14: ((13,1), 'The curve is the same L(jω) as in Bode. Encirclements of −1 test feedback stability; this Nyquist plot is different from the Nyquist sampling limit on the first page.'),
15: ((11,13), 'Changing a zero can change overshoot while poles stay fixed. Overshoot therefore is not always a measurement of damping ratio, and a zero of one input/output path need not be a zero of another.'),
16: ((4,12,15), 'Feedback places closed-loop poles. It does not change the poles of the unchanged open-loop plant model. Check actuator limits and delay after solving the ideal characteristic equation.'),
17: ((13,15,16), 'Lead adds phase near crossover; lag increases low-frequency gain with a slower tail. A notch targets a mode. Cancellation and stability margins depend on the actual model and delays.'),
18: ((2,4), 'Angle and velocity are separate state components. The matrix K maps the state vector to an input; it is not simply a stiffness. With u = −Kx, closed-loop modes belong to A−BK.'),
19: ((18,), 'LQR minimises state and effort cost. Q and R are weight matrices; xᵀPx is cost-to-go, not P alone. Later RL maximises return, so reward equal to negative cost reverses the value sign.'),
20: ((18,3), 'An observer estimates state from measurements and a model. Estimation-error poles differ from control poles. Faster estimation can also transmit more measurement noise.'),
21: ((12,18,19,1), 'Eigenvalues of A are state-space poles. Derive the growing modes of a simplified leg, then use a separate centre-of-mass model to check foot support. Physical growth time, sampling and software execution deadlines are distinct.'),
22: ((21,18), 'A fixed base removes whole-body tipping from this model, not every unstable joint equilibrium. Configuration changes inertia and gravity terms; local linearisation and deadlines still matter.'),
23: ((22,12), 'Superposition and fixed coefficients were assumptions of the earlier linear models. Saturation and contact can break them; a local pole test does not establish a global region of attraction.'),
24: ((23,4), 'Predict known dynamics with feedforward and correct residuals with feedback. Cancelling a model term does not remove physical inertia. Each nonlinear method needs its own assumptions.'),
25: ((5,6,11), 'This is the same J as in the flywheel lesson. At fixed net torque, more J means less acceleration. At fixed b, it gives a longer J/b time constant. At fixed desired acceleration, it instead requires more net torque.'),
26: ((25,11,15), 'Name the input and measured output first. Motor torque to motor angle, load torque to load angle, and imposed motor angle to load angle have different zeros. A natural frequency is not automatically a closed-loop bandwidth.'),
27: ((26,11), 'A parallel spring adds stiffness without splitting the rigid inertia. Negative apparent inertia at a frequency describes the spring’s contribution to torque/acceleration, not negative physical mass.'),
28: ((25,26,27), 'Compare the same port, output and controller constraints. A minimum-of-limits budget is a design estimate; a −3 dB bandwidth comes from a specified response. No topology has a universal Hz rating.'),
29: ((25,5), 'Use J_total = J_L + N²J_m, with N = motor speed / joint speed. This inertia affects acceleration and the speed-model time constant. High inertia, friction and stiffness are different properties.'),
30: ((21,28,29), 'Separate static support torque, acceleration torque and impact energy. They impose different requirements on the same biped actuator. A spring stores energy; damping dissipates it.'),
31: ((22,29,30), 'Moving a motor toward the base can reduce distal link inertia while its rotor still contributes reflected inertia through the transmission. Holding and accelerating are different torque requirements.'),
32: ((2,28), 'The plant describes what the machine can do; the objective says what it should do. Tracking and compliant interaction are different objectives. A state-to-input control rule connects to the later policy vocabulary.'),
33: ((4,32), 'A PD law uses virtual stiffness and damping. Finite gain allows error under load; feedforward or integral action can provide holding torque. Feedforward may appear in both position and impedance control.'),
34: ((33,7,1), 'I accumulates error over elapsed time; D estimates its rate. Both depend on timing. Saturation, delay and noise can invalidate an ideal linear response even when the algebra is correct.'),
35: ((33,29), 'The reference is desired torque or current. Current feedback can remain closed while position is open loop. Account for gearing, acceleration and losses before equating motor current with external joint torque.'),
36: ((33,35,11), 'Reuse the PD equation to specify interaction behavior. At rest, 0 = −K(θ_ss−θ_d) + τ_ff + τ_ext, using signed external torque. Holding on target requires τ_ff = −τ_ext.'),
37: ((36,5,7), 'With K_v = 0 and B_v > 0, force-to-velocity is first order with τ_c = M_v/B_v, just like J/b. Position still integrates velocity; with K_v > 0 the full position response is second order.'),
38: ((36,37,13), 'Impedance maps motion deviation to a force/torque command; admittance maps force/torque to a motion reference. A force sensor alone does not decide which controller you built.'),
39: ((33,35,36), 'K, B and feedforward are separate choices in a common torque law. A learned torque command depending on measured state contains feedback. Its derivatives describe local behavior, not necessarily a passive spring.'),
40: ((30,39,1), 'Schedule the same stiffness, damping and feedforward over gait phase. Gait phase means progress through a step; it is not frequency-response phase lag. Update rates are not joint bandwidths.'),
41: ((31,38,39), 'K times displacement bounds one spring-torque contribution, not every impact force. Damping, feedforward, inertia and delay still matter when the arm contacts its environment.'),
42: ((28,38), 'Mechanical compliance, low reflected inertia and a compliant control law are separate choices. State the required input/output bandwidth and loading when choosing an actuator.'),
43: ((25,42), 'At fixed density, mass scales as length³ and inertia as length⁵. Fixed-stress force capacity scales with area; torque also includes a moment arm. Compare capability and demand under the same scaling assumptions.'),
44: ((29,42), 'Use the same ratio, inertia and sensing definitions for a tendon drive. Tendon routing alone does not establish N = 1 or make motor torque equal joint torque.'),
45: ((20,26), 'Biological proprioception combines length, velocity and force-related signals. Tendon elasticity, passive tissue response and delayed neural reflexes are distinct; one measurement need not reveal the whole state.'),
46: ((45,29,20), 'Current estimates motor torque. External torque estimation also accounts for drivetrain and motion. Sensors provide information; the signal-to-command law determines the control paradigm.'),
47: ((46,36,1), 'Detection, interpretation and modulation of K/B are separate steps. Active compliance acts through feedback and delay; passive compliance already exists in the mechanics during a fast impact.'),
48: ((45,12), 'The feedback variable is force and its sign is positive. Gait-phase gating limits when that path acts, but a gate alone does not guarantee stability.'),
49: ((48,35), 'Activation changes force and force changes activation: that closes the loop. Convert current or joint torque into the units required by the force-feedback gain. A local gain test is not a complete biological stability model.'),
50: ((45,49,28), 'Muscle activation is a command, tendon force is a mechanical signal and joint motion is an outcome. Fast reflex and slow intent describe timescales, not interchangeable bandwidth numbers.'),
51: ((50,25), 'Compliance distributes deformation, damping dissipates energy and geometry changes load paths. These physical properties become part of the dynamics a later learning policy must operate within.'),
52: ((32,1), 'The agent chooses an action; the environment returns observation and reward. In this fully observed lake, observation equals state. One RL decision need not coincide with one physical control tick.'),
53: ((52,), 'A square is the state; a commanded direction is the action; slipping is a stochastic transition. Arrival at a goal or hole may pay a reward, while continuation after termination is zero.'),
54: ((53,), 'P(s′|s,a) describes the environment’s outcomes conditional on an action. π(a|s) describes the agent’s choices. A sampled outcome and an average over outcomes are different uses of the same dynamics.'),
55: ((54,52), 'R_(t+1) is one transition’s reward, not episode return or expected value. Changing rewards changes the objective even if the board and transition probabilities remain identical.'),
56: ((55,1), 'G_t starts with the next reward at weight 1, then discounts later rewards. It is a sampled future sum; V and Q will be expectations. Discounting counts RL steps, not necessarily milliseconds.'),
57: ((52,54,56), 'Policy randomness differs from environment randomness. A greedy action is best according to current estimates; an optimal action is best under the actual objective and dynamics.'),
58: ((54,55,57), 'The MDP collects state, action, transitions, reward and discount. The chosen state must contain enough information for the next outcome distribution. A policy acts within an MDP; it is not the MDP.'),
59: ((56,57,58), 'V^π(s) is expected future return conditional on state and policy. Past collected rewards are excluded. The same state under another policy may have a different value.'),
60: ((59,57), 'Q^π(s,a) fixes the first action, then follows π. It includes immediate reward and future continuation. Q is an action score, not an action or a physical torque.'),
61: ((59,60), 'Average Q^π over π to recover V^π. Constructing action scores from V by lookahead needs a model; policy gradients can instead use sampled returns and a V baseline without one.'),
62: ((56,61,54), 'Split return into next reward plus discounted continuation. Expectation equations evaluate π; optimality equations choose actions. Both still average over the environment’s outcomes.'),
63: ((62,59), 'Average over the policy action, then the successor state. Each branch contributes probability times (reward plus discounted continuation), not probability times reward times continuation.'),
64: ((63,60), 'The first action is fixed in Q^π, so the policy average occurs at the successor state. SARSA samples the next action from that policy rather than replacing it with a greedy max.'),
65: ((63,57), 'Replace the current action average with a max; keep the successor-state average. max gives a score and argmax gives an action. The agent still cannot choose how the ice slips.'),
66: ((64,65), 'Fix the first action and optimise the successor action. Q-learning uses a greedy continuation target that can differ from the behavior policy collecting experience.'),
67: ((63,), 'A sweep updates values computationally while π stays fixed. It is not an episode in the environment. A small update residual is a stopping test, not a reward.'),
68: ((67,65), 'Compare action scores using V^π and the model. Changing the rule is improvement; scoring the changed rule is evaluation. Resolve equal-valued choices consistently to avoid pointless switching.'),
69: ((67,68), 'Alternate evaluation and improvement. The stable flag means no strict policy improvement was found, not physical closed-loop stability. Finite-MDP guarantees need the stated discount and evaluation assumptions.'),
70: ((65,69), 'An optimality backup combines value updating with an implicit greedy choice. Extract a policy with argmax. The stopping tolerance and discount factor play different roles.'),
71: ((69,70), 'A backup differs by policy action versus max, but the algorithms also differ in scheduling evaluation and improvement. Both use the known model and target the same objective.'),
72: ((56,67), 'Estimate expected return by averaging completed sampled returns. Monte Carlo does not bootstrap from successor values, although the target value still satisfies its Bellman equation.'),
73: ((72,67), 'Keep π fixed; first-visit and every-visit choose which episode occurrences enter the average. An externally truncated rollout is not automatically a complete task return.'),
74: ((73,68), 'Combine sampled-return evaluation with improvement. ε-greedy behavior explores. Fixed ε generally leaves exploratory actions in the executed policy; optimal-limit guarantees need additional coverage and schedule assumptions.'),
75: ((58,74), 'A one-step bandit has no continuation: return equals immediate reward, and action value equals expected reward. Exploration still matters because that expectation is unknown.'),
76: ((71,72), 'Model-based means using dynamics/reward predictions for planning or learning; the model can be known or learned. A policy/value network alone is not a dynamics model.'),
77: ((56,74,70), 'γ changes time weighting, α changes update size, ε changes exploration and θ sets stopping tolerance. Different action arrows can still have equal value at ties.'),
78: ((70,77,12), 'A fixed-point theorem, an empirical plateau and acceptable task performance are different claims. A policy that stops changing may still be poor; convergence is not physical stability.'),
79: ((54,71,74), 'Trace edits to transitions, evaluation, improvement or exploration. The quoted C++ programs can encode directions differently from this app; use each program’s declared action encoding.'),
80: ((78,77), 'Backpropagation computes derivatives; Adam uses their first and second raw moments to change weights. Adam’s v is not joint velocity or gradient variance.'),
81: ((18,80), 'A neuron extends a weighted sum with bias and activation. Without nonlinear activations, stacked affine layers stay affine. Bias b is not mechanical damping b.'),
82: ((81,57), 'Gradient flow multiplies weights as well as activation slopes. softmax gives probabilities; argmax gives an index. The latter is not a differentiable action distribution.'),
83: ((81,82,1), 'A forward pass computes predictions, not learning updates. Fixed network size helps bound computation, but actual execution must still meet the control deadline.'),
84: ((83,80), 'Multiply sensitivities along a path and add them where paths merge. Backpropagation yields a derivative; the optimiser and learning rate turn it into a parameter update.'),
85: ((84,60,78), 'A critic fits value targets; a DDPG actor minimises negative predicted Q. Lower training loss does not necessarily mean higher evaluated return.'),
86: ((81,80,85), 'Scaling conditions units, normalisation conditions statistics, regularisation changes the objective and clipping limits a gradient. None is the same operation as limiting actuator torque.'),
87: ((60,81,78), 'A parameterised V or Q keeps the expected-return definition. Approximate sampled backups do not automatically inherit the exact tabular contraction guarantee.'),
88: ((71,87,57), 'Critic and actor perform approximate evaluation and improvement. Deterministic/stochastic choice is separate from on/off-policy learning: SAC is stochastic and off-policy.'),
89: ((88,66,84), 'A target actor supplies the successor action; it is not an exact max. Here τ is a target-network mixing fraction, γ discounts reward and learning rates scale parameter updates.'),
90: ((89,84), 'The critic’s action derivative is the actor’s backward seed: local sensitivity, not a target action or confidence. Include physical-unit scaling in the chain rule when the critic uses physical actions.'),
91: ((60,90,83), 'Q requires state and action. Their merge point changes the derivative path to action; a shorter path is a design choice, not a guarantee of better value accuracy.'),
92: ((58,76,88), 'Dynamics-model use, policy randomness and data reuse are three independent distinctions. DDPG does not require a unique best action at each state.'),
93: ((92,66), 'Replay and rollout storage preserve different information for their updates. Termination removes continuation value; external truncation need not. Resetting and zeroing a bootstrap are separate decisions.'),
94: ((36,89,58), 'The action here changes stiffness-profile weights once per gait cycle; it is not torque or a 1 ms tick. Landmark errors are observations, while the controller and person have a richer underlying state.'),
95: ((1,94,93), 'Control ticks, gait-cycle decisions and learner updates use different clocks. A 20 Hz trainer is not a 20 Hz joint bandwidth. The fast task must not wait for the trainer.'),
96: ((1,6,8), 'The hip exoskeleton runs a 1 kHz admittance task inside 4 kHz drives, and its measured assistance bandwidth is 5 Hz. Loop rate, actuator bandwidth and the 200 ms human response window are three separate numbers.'),
97: ((2,96), 'Three segment angles and three rates are six states; whole-body angular momentum about the stance foot is one scalar output computed from them. Choosing that output is what makes the plant a momentum regulation problem.'),
98: ((3,97), 'Segment mass, length, centre-of-mass offset and inertia are scaled from height and weight; rendered stiffness and damping are identified on a bench. Scaled anthropometry and measured device parameters are different kinds of number.'),
99: ((12,16,97), 'The linearised frontal-plane body has a right-half-plane pole whose magnitude is a doubling time. The wearer closes that loop with delay and a torque ceiling; the exoskeleton adds torque in parallel and does not replace it.'),
100: ((8,13,99), 'Bandwidth here was measured with a 1-100 Hz sine sweep on the loaded device, not derived from J and b. Above that corner the rendered admittance fades and reflected inertia is what the wearer feels.'),
101: ((37,97,100), 'The commanded quantity is a momentum error, not a pose error, and the output passes through a dead zone, an asymmetric distribution, a 2 Hz filter and an admittance block before reaching the joint.'),
102: ((7,20,101), 'Momentum is estimated from three IMUs and a scaled segment model, never measured. Gyro bias integrates, and a biased model biases the reference torso state rather than the sign of the correction.'),
103: ((29,36,37,38), 'A 100:1 harmonic drive reflects rotor inertia by N squared and removes backdrivability, so interaction torque is measured and motion is commanded. Very low virtual M, B and K make that admittance behave as a torque source.'),
104: ((96,99,101,103), 'Reported group percentages, effect sizes and p-values are measurements; the survival curves drawn beside them come from a teaching model. Beam distance is a validated balance assessment, not a fall-rate measurement.'),
105: ((1,34), 'The injected fault lasts 200 ms, shorter than the 200-250 ms volitional response, so the measured deviation is mechanical rather than voluntary. Persistence window, detection time and filter group delay are separate parts of one budget.'),
106: ((2,20,105), 'Axial load is robust to control faults and knee angular velocity is sensitive to them, so one is the model input and the other is the detected output. Load alone is ambiguous within a stance phase; its derivative resolves that.'),
107: ((11,36,106), 'Finite-state impedance control is a piecewise second-order law with a stiffness, damping and equilibrium angle per state. A locomotion-mode misclassification substitutes another set, which is a different virtual mechanism rather than a torque spike.'),
108: ((13,20,107), 'The detection threshold tracks the predicted mean and spread through the gait cycle, and a persistence test requires consecutive exceedances. The multiplier k is chosen by the asymmetric cost of late detection versus false alarm.'),
109: ((12,36,108), 'The supervisory layer interfaces only through an additive torque, and evaluates one learned map at both the nominal and the measured state so model bias cancels. The baseline controller stays engaged throughout.'),
110: ((107,109), 'Compensation is scaled by the momentum deviation and held to the end of the stance sub-state, which is different from a predefined on-off corrective action applied regardless of severity.'),
111: ((20,110), 'The Gaussian process models predict nominal behaviour from a robust input and supply the variance the threshold is built from. They are observers of normal operation, and they depend on the sensors they are fed.'),
112: ((1,108,111), 'Every residual failure in the study was a late detection: 43 ms worked, 103 ms did not. Detection latency, not false-alarm rate, is the quantity the outcome measures respond to.'),
113: ((105,110,112), 'Sensitivity, momentum deviation, margin of stability, handrail use and perceived severity are five separate channels agreeing on one mechanism. The layer compensates faults; it does not prevent them.'),
114: ((2,22,24), 'The control pages assumed a plant M(q)q̈ + c + g = τ. This block derives it: configuration, pose, Jacobian, statics, then dynamics. Configuration space and task space are different spaces with different dimensions.'),
115: ((114,), 'Degrees of freedom count the numbers needed to place every point of the robot. Gruebler counts them from links and joints but assumes independent constraints; the topology of C-space (a torus for two revolute joints) matters as well as its dimension.'),
116: ((115,), 'Topology is the shape of C-space and is fixed by the robot; representation is the numbers you store and is your choice. Joint angles live on circles: wrap their differences. Orientation lives on SO(3): explicit angles blow up somewhere, so store R or a quaternion.'),
117: ((116,), 'A holonomic constraint g(q) = 0 removes C-space dimensions; a nonholonomic velocity constraint A(q)q̇ = 0 removes velocity freedoms only. Task space is a choice of coordinates for the job; workspace is the reachable part of it.'),
118: ((116,), 'R ∈ SO(3) represents an orientation, changes frames and rotates vectors. Exponential coordinates ω̂θ are a local three-number chart; Euler angles have singularities, so compute with R or quaternions and express orientation error with the matrix log.'),
119: ((118,), 'A twist V = (ω, v) is a rigid-body velocity; v in the spatial twist is the velocity of the body point at the space origin. Wrenches F = (m, f) transform with the adjoint transpose so that power VᵀF is frame independent.'),
120: ((119,117), 'Product of exponentials: home pose M plus one screw axis per joint. Space-form axes are drawn at home in the fixed frame; body-form axes in the end-effector frame. D-H is an alternative parametrisation, not different kinematics.'),
121: ((120,), 'J(q) maps joint rates to the end-effector twist. Column i is joint i moving alone. The velocity ellipse has the singular values of J as semi-axes; a singularity is a rank drop, not a large number on a display.'),
122: ((121,119), 'τ = JᵀF follows from power balance and holds only for static, lossless conditions; gravity torques are added separately. The force ellipse has the same axes as the velocity ellipse with reciprocal lengths.'),
123: ((120,121), 'Inverse kinematics can have zero, finitely many or infinitely many solutions. Analytic solutions use atan2 and give every branch; Newton–Raphson needs a seed and can converge to another branch; damping bounds steps near singularities.'),
124: ((121,123), 'For a redundant arm, null(J) has dimension n − rank J. N = I − J⁺J projects a secondary joint motion so that it produces no hand velocity. A torque-level null space needs the dynamically consistent inverse instead.'),
125: ((115,121), 'Closed chains split joints into actuated and passive. Loop-closure equations give passive rates from actuated ones; parallel robots have easy inverse and hard forward kinematics, and actuator singularities inside the workspace.'),
126: ((22,24,121), 'Euler–Lagrange produces τ = M(q)q̈ + c(q,q̇) + g(q). M is built from centre-of-mass Jacobians; c contains Coriolis (q̇ᵢq̇ⱼ) and centripetal (q̇ᵢ²) terms; g is the gradient of potential energy.'),
127: ((126,29), 'M(q) is symmetric, positive definite and configuration dependent. With Christoffel-symbol C, Ṁ − 2C is skew, which makes the arm passive from τ to q̇. Reflected rotor inertia adds to the diagonal and reduces coupling.'),
128: ((126,119), 'Recursive Newton–Euler computes inverse dynamics in O(n): an outward kinematic pass with gravity as a fictitious base acceleration, then an inward force pass. The joint torque is the moment component along the joint axis.'),
129: ((128,24), 'Inverse dynamics evaluates τ for a given motion; it does not simulate anything. Inertial and velocity terms scale with 1/T² under time scaling while gravity does not. Its uses are feedforward, sizing, feasibility and contact estimation.'),
130: ((128,127,10), 'Forward dynamics solves M q̈ = τ − h for q̈; M is always invertible. Integration is a separate choice: explicit Euler adds energy, semi-implicit Euler is symplectic, RK4 is accurate per step but can drift over long runs.'),
131: ((127,122), 'Task-space inertia Λ = (JM⁻¹Jᵀ)⁻¹ is the inertia felt at the hand, direction and posture dependent and unbounded at singularities. J̄ = M⁻¹JᵀΛ is the dynamically consistent inverse.'),
132: ((117,130), 'Constraint forces enter as Aᵀλ; λ is the contact force and the constraint does no work. Real contacts are unilateral: a solve that requires the surface to pull means the contact would break.'),
133: ((129,), 'A path q(s) is geometry; a time scaling s(t) sets speed along it. Cubic scalings jump in acceleration at the ends, quintic ones do not; trapezoidal profiles are time-optimal under velocity and acceleration limits.'),
134: ((133,129), 'Along a fixed path, torque limits become state-dependent bounds on s̈. The time-optimal scaling saturates some actuator at every instant, switching from maximum acceleration to maximum braking.'),
135: ((115,133), 'Planning happens in C-space: workspace obstacles map to C-space obstacles. Grid search, sampling-based planners and potential fields trade completeness, optimality and dimension; the output is a path, not a trajectory.'),
136: ((24,127,129,11), 'Computed torque cancels M, c and g so joint errors follow a designed linear system; model errors become disturbances. PD with gravity compensation needs only g and is globally stable for set-points by the skew-symmetry property.'),
137: ((124,131,136), 'Operational space control applies F = Λ(ẍ_d + K_d ė + K_p e) + μ + p through τ = JᵀF. Posture torques must pass through I − JᵀJ̄ᵀ with the dynamically consistent J̄, or they disturb the hand.'),
138: ((36,37,38,132,137), 'In contact, each task direction is either motion controlled or force controlled, never both. Hybrid control separates them with a selection matrix; impedance control specifies their relationship and is the robust default with passive environments.'),
139: ((119,122), 'A frictional contact contributes a cone of forces. Force closure means the cone-edge wrenches positively span the wrench space; form closure uses geometry alone and needs more contacts.'),
140: ((117,121), 'A differential drive has two inputs for three pose coordinates and a nonholonomic no-slip constraint. It can reach every pose but cannot be smoothly stabilised to one; track a look-ahead point or a moving reference instead.'),
141: ((114,124,131,136,137), 'Answer robotics questions one level below the controller: spaces, kinematics and Jacobian, the equation of motion, then the control law built on it.'),
}

VOCABULARY = {
    'Control': 'τ in mechanics is torque (N·m); τ_c is a time constant (s). Bare τ in first-order formulas means τ_c. Excitation ω = 2πf is angular frequency, while θ̇ is joint angular velocity. Both use rad/s but are different quantities. k/b are physical stiffness/damping; K/B or K_p/K_d are controller stiffness/damping. ζ is dimensionless damping ratio. Standard first-order rise time is 10–90%; settling uses a 2% band around the final value, which need not equal the reference.',
    'Interaction': 'Mechanical impedance normally means force/velocity or torque/angular velocity. Force/displacement is dynamic stiffness; admittance is the inverse for the same convention. J_eff inferred from torque/acceleration can include elastic effects; negative apparent inertia does not mean negative mass. Motor torque, joint torque and external torque differ. N is motor speed / joint speed.',
    'Learning': 'Reward r = R_(t+1) is one payout; return G_t is the discounted future sum; V and Q are expected returns. max gives a value, argmax an action. x in control and s in RL denote state; observation is measured information and need not be a complete state. α is an RL learning rate but angular acceleration in mechanics. LQR Q is a cost matrix, not an action-value function. Deterministic/stochastic describes action selection; on/off-policy describes the data and learning policy relationship.',
    'Networks': 'A gradient is local sensitivity, not confidence. Backpropagation computes gradients; the optimiser changes weights. Adam v is the second raw moment, not velocity or variance. τ in DDPG is a dimensionless target-update fraction, not torque or time constant. Normalisation, regularisation, gradient clipping and action limiting are different operations.',
}


def resolve_connections(classes):
    by_num = {cls.NUM: cls.__name__ for cls in classes}
    return {by_num[n]: Connection(text, tuple(by_num[p] for p in previous))
            for n, (previous, text) in REVIEW.items()}
